import os
import sys
import threading
import tkinter as tk
import customtkinter as ctk
from tkinterdnd2 import TkinterDnD, DND_FILES
from tkinter import filedialog
from PIL import Image, ImageDraw
import base64
import tempfile
import webbrowser


PROGRAM_ADI = "EXIF Yok Edici 3000"
PROGRAM_SURUMU = "1.1"
PROGRAM_GELISTIRICI = "tyyaman"
GELISTIRICI_BAGLANTISI = "https://github.com/tyyaman55"

DESTEKLENEN_UZANTILAR = {".jpg", ".jpeg", ".png", ".gif", ".bmp", ".tiff", ".tif"}

FORMAT_ESLEME = {
    ".jpg": "JPEG",
    ".jpeg": "JPEG",
    ".png": "PNG",
    ".gif": "GIF",
    ".bmp": "BMP",
    ".tiff": "TIFF",
    ".tif": "TIFF",
}

SIMGE_TABAN64 = """AAABAAQAEBAAAAEAIABoBAAARgAAACAgAAABACAAqBAAAK4EAAAwMAAAAQAgAKglAABWFQAAQEAAAAEAIAAoQgAA/joAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAAMIOAADCDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGZOLQBWQScebVQua087IDYAAAADHxQJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEIvFgAbEAUJims5n7GNTv+xlFvkl3xKilxGJCYAAAABFgwDACkZCwZqUzA9fGM9YX1kPWJ9ZT9ie2Q+YntjPmJ0WzZgcV9Gg7qfcPThwXz/8NKK/+LDfv6/ombfj3RFgFhCJB+EakNtv6Fo7dGxdP/RsnP/0bJy/8+wc//Gpmv/qIlT/6KRd//b1MX/8ubL//HbpP/x1Y//8NKK/9/Cfv6ljlvCtZ1v1+bIif/mx4b/5seG/+TGhP/LrXL/qZFm/5KBZP/AtqX/7unh//Lu6v/x6+L/8uXG//Hbov/x15H/tqRz38axhunrz5L/6cyM/+jLi//RtXz/q5p8/7+4rf+VjH//lIl5/+Db1f/08Oz/8u3p//Hs6P/y7OL/39O0/4d5WpTJtIvq79WY/+3Rkv/ozY7/uKN9/8S+tP+Admr/aFxO/2VZSf94bl//sKie/+Pe2f/08Oz/8+/t/7mtm/9yWjiGyreP6vLZnf/x1pj/4caM/7+xm/+nnpP/ZllJ/1hKOv9URzf/YlZH/2pdTv+km43/vLWo/8zEuP+1nnL/kHRGiMu5k+r13qP/9Nud/9/Hjf/Gu6j/npSI/2haSv9mW0z/UEMz/1pMPf9wY1P/urOm/6qWbv/NtHv/2b2A/5F1SonHtpLq896m//HaoP/kzZX/xLeg/7Wtov94alr/c2ZW/1xOPf9hU0P/hnlr/8W9sv/Fr3//7NKT/9/Eif+RdkyIm45767mslP+4qpH/tqiQ/6icif/SzMP/pZqM/4J0Y/95bFv/h3tr/8O6sP+zqp7/rJ2G/7ipkP+un4X/eGhQiMK8tObv6uf/7ejk/+3o5P/k4Nr/wruw/9HLw//MxLr/xb2z/8/Iv//BurH/0szD/9rTy//GvLL/3tnS/42DdoSrpJml6OTf/vPu6//z7+v/9PDs/+zn4v/PycD/xb2z/8O7sf/GvrT/3tfQ//Lu6f/b1Mv/wreq/83HwOt3bWBJZVpLGpiOgZmuo5j9s6ic/6yilfvGv7b19PDs//Ds5//u6eX/8u7q/9zY0/Spn5XTsaed/qmflOqDem5cAAAABFpMOgBWRzUVdWhXWXtuXWJvYVBWfXJjYMfBudbd2dT44NvX+tHMx+ydl46GSj0uJHVpXFxrX09FKRoGBDUmFAAAAAAAAAAAAAAAAAAAAAAAGRAHAAAAAAFjWEokgXhrVYV8cV5vZVo7NCkeCEQ4KwAAAAAAAAAAAAAAAAAAAAAA/4cAAP8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAQAA+B8AACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAMIOAADCDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKB0fAAwJCwcQCw0KAQADAQIBBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALyojAMGAHgBBLx49Yksrq2lRLbtINiFuJhsTGP///wAEAwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADkyNgA9LxwANSkaLXVaNNiuiUn/rIVF/39jOPxvWDLNTjsfaCQaDhJRPh8AAQABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOCkYABUMCAheSCajr4tL/7+WTv/HomD/38B9/96/eP+ylFj6dl0zwkgzGVYiFQcOQywRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAEAAAABQAAAAUAAAAFAAAABQAAAAUAAAAFAAAABQAAAAUAAAEFAAAABQAAAAUAAAACRzckU5Z7SfTGnVL/x59X/+fJhv/w04z/7tCI/+3Ohv/au3b/qYxT93NZMLpDLxhTFw8JDC8gEgAAAAAAJRUMAAgAAAI/LRk+WkQmlWhRMbFpUTCzaVEvsmhRMLJpUzOyaVMzsmZRMbNnUjOxZ1IysmZRMLNlTy6zY0wutFM+IrJxYk7czb+m/8+xfP/hw37/8taS/+/SjP/v0ov/7tCJ/+7QiP/tz4j/2bl1/6KFTvZoUS2zQi8aQAoCBAMAAAAATzkhXY1xROnComb/z69w/9Cvcf/Qr3H/0K9w/9CwcP/QsHD/zq5w/82tcP/Lq2//yalt/8OjZv+0klj/f2M6/6ufjv/Ty7z/3NTD//Poy//z3KX/8NWQ//DTjf/w04z/8NKL/+/Siv/u0Yn/7c6H/9a4c/+Ve0jnSTYfWT8pGDmLcEXg3b18/+TEgf/iwoD/48KB/+TDgv/jw4D/5MR9/+TEf//hw4H/3r+A/9e4e//QsHL/x6Vm/6GASv+NemD/z8a1/9DHt//q5t7/9fHt//Pt4f/y5MH/8dqh//DVkP/x1Y3/8NSL/+/TjP/u0ov/79OK/93EgP9tXTzKYkwwlcmud//oyYn/5MWE/+TFhP/kxYT/5MWE/+TFg//kxYH/48SB/9/Agf/Xt3r/x6Zp/6mKU/+LcUL/aVU2/7esnP/QyLf/3djL//Tv6//y7en/8Ozo//Lt6P/y7N7/8uTB//Lanv/x1Y//8NWN//DUjv/w1I3/5tCP/3lrTt1/blHC4cmT/+jKi//myIj/5siI/+bIh//myIf/5siG/+XHhv/gw4T/1rh7/7KTXP+Ca0b/hXZh/6OXhf9zaFX/ua+e/9nPvv/w7Ob/9O/q//Ls6P/w7Of/8Ozo//Ds6P/x7ej/8+zc//LjvP/x2pz/8tWQ//PZkf/Qv4r/YlQ/oIp6YM3m0Jz/6s2P/+fLjP/ny4r/6MqK/+fJif/nyYn/5MeJ/9u+gv+qjlz/fWtR/7mxpP/j3tT/5ODW/6GZi/+MgW7/39TB//j18f/z7uv/8uzn//Hs5//w7Of/7+vm//Hs5//x7ej/8u7o//Ls2//y47n/8Nyg/5qObOZAMSI7jXxizunToP/t0JP/6s2Q/+nNjv/pzY3/6cyM/+jLjP/jxov/uZxo/4RzW//PyL7/5+Pc/7u1rf+CeGv/ZVpL/1VHNv98cGD/ysa+//Ty7//18e3/8uzp//Ls6P/y7Of/8uzn//Hs5//w7Of/8O3p//Pw6//PyLj/WUw3yzIhERONfGLP6tSj/+7Tlv/t0ZP/7dGR/+zQkP/rz4//6c6Q/9e7gv+HclP/yMK3/+rn3v+impD/W00//2FUR/9uY1b/cGZX/2RYRv9dUD7/j4d5/9nVzv/18u//9PDs//Ht6f/x7Of/8u3o//Hs6P/w7On/7uzo/5iMeP9jTS3ROisXF458Y9Hs16f/79aZ/+3Ulv/u05X/7dKS/+3Rkv/rz5P/tJpp/6KVhP/u6+T/tK6k/15SRP9uY1f/dmpc/2pdTv9lV0f/ZFdI/3BkVP9fU0P/YldG/5SLf//W0sv/9PLu//Xx7f/y7ur/8+3q//Xw7f/KxLz/lX1V/4VpP9QuHQ8Zj35k0O3Zqf/w15r/79aY/+/WmP/v1Jb/79OW/+fMkv+Uf1r/zsa7/+Xg1/91aVv/b2NX/21eUP9aSzn/XVBA/1xQQP9fUkP/Wk4//3lsXf9lWUv/V0g2/4N5af+fmIv/29jR//bz8P/49fH/7+zp/5WHc//Bo2n/im1B1CsdEBmNfGPQ7dqs//LZnv/y15r/8daZ//DWmf/v1Zf/4ceN/49/Yv/l4Nr/x8C1/2lcTf94bF7/VkYz/1tOPf9LPzD/QDIh/1ZJOv9eUkX/XlFC/3RoW/9iVUT/u7Ol/7GomP9sX0v/n5aH/8O/tv+akIP/o4te/+DCgf+IakDVLh0TGo18ZNDu3K7/89yh//PanP/z2Zv/8tmb/+/Ymf/dxIr/lodu/+3q5f+2rqL/dWhZ/3JlVv9aSzv/Y1ZG/0o+Lv9ENyb/PzAf/2BURf9bTTz/cWVW/2NVQ/+4sKP/39vQ/39uUv+qkFv/o4xc/7eeaf/jx4f/4sWF/4ZpP9UuHRIajn1l0fDesf/136T/9d2g//Tbnv/z253/8tmc/+HHjv+Xhmz/7url/7qypv95bFz/dWha/15QQP91aVr/gnps/2ZdT/9CMyL/YFNE/1NEM/9xY1T/ZVZF/721qf/f3NL/inlc/9u+gf/pzYz/7M+O/+vQj//lyIn/hmpA1S4cEBqNfGTR8N+0//fhp//34KT/9d6h//PdoP/z257/6tGX/5iGZP/l4dv/0svC/3lsW/+GeWv/XE06/4h9b/+JgHT/V0s8/11OPv9RQzL/Wkw9/3lrXf9uYE//2NHI/9TPxf+QfVr/58uN/+zRkf/t0pH/7dOS/+jLjf+JbEPULBsPGox7Y9L047r//Oet//vlqv/646j/+OOn//fgpv/24Kb/r5tw/83Hvv/w7ef/joNz/4d7bP+Ac2T/YE45/19NO/9aSzr/Tj8s/1pLO/94bV7/dGdX/5WJev/w6+X/tq6k/66ZbP/y2Zv/8tma//Pam//z2pv/7tKU/4pwR9QnGAwZaVpG06aYf/+rm33/rJt7/6ubev+rm3r/qpt6/6qbef+OfV7/lYl6//bz8P/UzML/g3Ri/42Bc/+KfW3/eWtY/3JjUf92aFf/gnZn/31wX/+Cc2H/2dHI/+rm4v+AdGX/koFh/6aUcv+llHL/p5Z1/6aVdP+ikGz/aVU50i8iEhdrX0/TqqCT/66ilv+toZX/rKCU/6yfkv+soJL/raGT/66jlP+Qg3D/w7yz//n28//Px7z/iXxr/4R3Zf+JfW3/iXxt/4R4aP95bVr/iXtp/9fPxv/z7+v/rKab/5GGdv+soZT/qp6S/6ugk/+toJP/q6CT/6qfkf9vYU/ULiEQGYV9cdTw7Oj/9fDs//Tw6//07+v/9O/q//Tv6v/z7+r/8/Dr/+Hb1P+Xi3r/ysS7//j28v/o49z/wLap/6aZif+bj4D/opiJ/8C3q//q5Nz/8+/q/7ewpv+Zjn//5uLa//Pt6P/z7ej/8ezm//Lt6P/w7Of/7ejh/4l9btckFwcbgXdqxOzo5P/07+z/8u3q//Ht6v/y7er/8e3q//Ht6f/w7en/8e/r/9/Z0f+Xi3r/sKie/+bj3v/49PD/+vXw//nz7v/48+//9PHt/9/b1v+imo//m5CD/+Tf2P/v7OX/8Ozl/7uxpf+Hd2L/wruv//Dt6f/p5d3/gHZnyxkKABNmWkeH08/H/vf08P/z7uv/8+7q//Pu6v/z7ur/8+7r//Lu6v/y7ur/9PDt/+rk3v+5sab/mI5//6OZjP+1raP/u7Sq/6+on/+ckob/mI19/720qf/q5uL/8e3p//Ds5//w7ef/rJ+P/29ZPv+wo5T/9fHt/9nUzf9nW0ycAAAAAz0uFyaOhXbM5+Pe//j18v/48/D/+PPv//jz8P/49O//+PPu//fz7v/28e3/8+/r//Pv7P/p5d7/0sq//7yzpv+1q57/u7Gl/9LJv//r5N3/8+7p//Lt6P/07+r/9fHs//Xx7f/z7ef/6eHa//Pt5//s6OT/l5CG5EE0JjpJPS8AcmlXAE0/LTiEeWvAtq+k+ca+t//IwLj/ycC4/8nBuP/Jwbj/ysO5/9rVzf/z7+v/8u7q//Hu6f/z8Ov/9PDr//Tw6//z7ur/8u3o//Hr5//x7Of/6+bh/8zFvv/Iv7j/x763/8e+tv/Jwbn/vLWs/YmAddRMQTFRAAAAATUqGgADAAAAaE0mACUTARFXRzWkkYNz/5uOff+ajnv/m458/5uOfP+Fd2T9aFtI6tfRyf328u//8e3p/+/s6P/v7Oj/7+zo/+7r5//u6+f/7uvn//Dv7P+wqqL0UEEyhGJTQ82bj4L/oJWJ/5uQgv9jVUPTKhsLJ///0gANAwAAAAAAAAAAAABNRTMAVkc2AFBCMTVuYlKid2xds3drXLJ3aluzeGtbtGpdTJpAMyBLhntszN/a0//28/D/9fLv//Pw7P/z7+z/9O/r//Pw7f/y7+3/xMG8/2deUZsMAAAIU0Y4TW1iVapzaFqvcGRWq1ZJOVoAAAABRTgqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAFAAAABQAAAAUAAAAFAAAAAmtaRgBAMyIwem9gsLKrovPPysT/3NjU/+Dc2P/b19L/ycW//6Kck+piWUyOLSIQFjguHAAAAAAAAAAAAwAAAAQAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADooEwAjFQgMRjkoQFtPPnlnXU2Qa2BRlmVaTJBUSDxuOy0fMRQFAAUfEAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA///x////4P///8A///+AD+AAAAOAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAAAABwAAAB+AAAAfwIAMf//AH//////8oAAAAMAAAAGAAAAABACAAAAAAAAAkAADCDgAAwg4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC8rJQAtLCkCMigdIjcqG0Y2KRs5MSkfDTUmFQAlMDsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOi0lADUrKQc9LBxvWEMm3nJZMvhoUCzxRzYhtTkrHUkwJR0KOSgYAAEiRgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0Lh8AnzsMADosHWhrUS/1rIdJ/7mRTP+thUT/dFcv/1A9IvJHNR2vNSYXRikgFgcvJBUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADsvQgA4LBkAMycXL1dDJt6vjE7/v5hQ/7uRS/+1jUz/sY9W/8GjY/+sjlP/clgu8Ug2HKI0Jxk2KR8iAy8jHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0xIQAxKSEIRTIboZN0P//FnVX/vpZO/7+VTv/TsXH/7M+M/+/QiP/uzoP/3rx0/6iJT/9mTinoRDAXkDUmFC4lIx0DLSUaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDQmAD4tGAA7KxpRblYt88KbUv/GnFP/v5RM/8+pY//t0ZD/79KL/+7QiP/tzob/7M2F/+rLg//UtG//nX5I/2dNJuRDMBeMMSMXKysgHAIvIhoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMSUcACwlHgUvIhgbMCMZKzMkGi80JRcvNCUVLjUkFS40JRguMiYZLjQnGi42KBwvMiYZLy8lGC4xJhstNCgcLTUpHi80KRwwMycZLzImGTAzJxkxMSUWLzgoFTVSQi7BtKF+/82raf/Em1H/yqFX/+jNiv/x1ZD/7tKL/+/Riv/u0In/7M+I/+zOh//rzof/6suE/9O0cf+be0b/XkYk4jwrF4YsIhYlKCAuASsiIAAAAAAAAAAAADgmGwAwIh8BNycYNUMwGqFXQiTbZE0t6mVNLuxmTS3sZk4t62VNLOtlTi7sZU8w7GdQMexmUDDsY04u7GJOLuxkTzHrZE8w62JNLexiTSztYkwr7GJLK+1gSSztWkQo7Ec0G+2HeWf82NDC/9bIr//PsHr/4cN+//PamP/x1ZD/79KN/+7SjP/v0ov/79GJ/+7QiP/tz4j/7M6I/+3PiP/qy4L/zq1q/49yP/5XQiPbPiwacTEkGhA0JBkAPjAlAABRyQA9KRlRXkcn4J9/TP/HpWf/0bFw/9Kxcf/TsnL/07Fy/9Kwcf/SsHD/0rFw/9OycP/SsXD/0a9w/9CucP/PrnD/z61w/82rbf/NrG3/yqlq/8KgYv+3lFr/lnVC/2hRN//CuKn/1Mu9/9LJuf/b0sH/8ujK//Tepv/y1pT/8dSP/+/Tjv/w043/8NKL//DSi//w0ov/79KK/+7Qif/sz4j/7c+I/+rKgv/NrWn/im4+/Ek1G50xJR0QPikXADknGj5lTCvivZ1j/+PBf//iwX7/4MB9/+HAfv/jwYD/4sF//+LBf//iwX7/48F9/+PBff/iwn7/4cF//9+/f//evn7/27t9/9e4e//Vtnj/z69x/8WkZP+2k1b/c1ct/5iLd//Ty7z/zsW1/9DJuP/r593/9/Pu//fv4P/y5L//8Nmd//HVkP/x1I//79SO//DTjv/w1Iz/8dSK//DTi//u0Yv/7dCJ/+7RiP/v0of/5sqA/4JqP/c4KhltNyceEFA4H7avkVv/5saE/+PEgv/iwoD/4cF//+LCgP/jwoL/48OC/+PDgv/jw3//48R9/+TEfP/jxH//4cOB/9/Bgf/cvX//17h7/8+xdP/Kqmz/xKJl/7yZW/+Nbj3/c2BI/8/Es//QyLf/zcOy/9zVyP/08e3/9PDr//Pv6v/z7un/8+va//Hiu//x2Z7/8NaR//HWj//x1Y7/8NWM//DUi//v043/79KM/+7Si//t0Yn/8NeM/7imcf9GNyPAPSkaTX1jPvLixoj/5siI/+XFhf/kxIP/5MSC/+XFhP/kxYT/5MSD/+TFg//kxYL/5MWA/+TFgP/jxIH/4cKC/92+gP/Wt3v/zq1x/8imaP+/nV//q4tS/5F2RP9eSSv/q5+Q/9XMvP/NxLL/0cq6/+3q4v/18Oz/8u7p//Dt6P/x7Oj/8u3p//Lu6P/y69n/8uK7//Ham//y1pH/8dWP//DWjf/w1Yz/8NSO/+/Tjf/v043/8diO/8a3h/9MPinQRjQdiKiSaf/t0pb/6MmJ/+XGh//lxob/5ceG/+XHhv/lx4b/5ceG/+XGhf/lxoX/5caE/+TFhP/hw4P/3sCC/9e4e//NrG7/u5tg/5F1R/9oUzH/X04z/1xNNP9QQy//wrmp/9HJuf/OxbX/497U//by7f/z7ur/8e3o//Hs5//w7Of/8ezn//Lt6P/w7un/8u/o//Pr2P/y4bT/8NiZ//DWkP/x1o//8dWP//HUj//w1o//8tuT/62gef9FNiSuUkEqpMOwi//t0pb/6MuM/+bJiv/myIn/58iJ/+fJiP/nyIf/5siH/+bIh//myIf/5ciH/+PFhv/ewYT/1rh9/8qrbf+ggk//aVIy/2xeSv+bj3//xLqr/760ov9YTDr/s6mX/9XLuP/b0cD/8/Dr//Xw7P/z7un/8u3o//Ls5//v7Oj/8Ozo//Ds6P/v7Of/8ezn//Lt6f/z7+f/8+rT//HhtP/w2Jj/8tWQ//LWkf/y2ZD/7Nqd/39zWfM9LR5WV0Yxrsu6l//t05j/6s2Q/+jLjv/nyov/58uK/+jLiv/oyYn/58mI/+fJiP/nyYj/5cmJ/+LEiP/avYL/zK5y/41yRf9fTDX/nZKD/9nTxv/m4NX/49/U/97Yzv+GfW7/g3hm/9nNtv/n2sT/+Pby//Pv7P/y7en/8uzn//Hs5//w7Of/8Ozn/+/s5//v6+b/8ezn//Hs5//x7ej/8u7p//Tv5//z69P/8uCv//LZlv/z3JT/wraO/1RGM7U4Kx0OWUgzsc28mf/w1pz/7M+S/+nNkP/oy47/58uL/+jMjP/oy4v/6MqL/+jKiv/nyor/5MiL/9/Ch//TtHr/kndM/2dWQv+6sqT/5d/W/+Xh2f/n497/2tfP/7u1rP+MhHb/TD4s/5CFcf/Xzr//+fj2//Xy8f/z7+z/8u3p//Ls5//y7Of/8+zn//Ls5//x7Of/8ezn//Hs5//w7Of/7+zn//Dt6P/x7ur/8+7n//Tq0P/q3bP/eW5W/T4vH19DNCAAW0k0sM6+m//x2J//7dGU/+vPkv/qzZD/6s6O/+rOjv/qzo7/6c2N/+nMjP/ny4z/48eN/9q9g/+jh1f/ZlY//8S7r//o49r/5+Pc/9zZ0/+bk4n/YVRF/09BMf9RRDP/Vkg3/05AL/9fU0L/q6WZ/+7t6f/59/X/9PHt//Pt6v/y7On/8uzo//Ls5//y7Of/8uzn//Ls5//x7Of/8Ozn/+/r6P/v7Oj/8O3p//Xy7/+7tav/Sjwn/EMzIFVFNCEAW0k0sc++nP/x2aD/79OW/+3RlP/t0ZP/7NCR/+zQkP/s0JD/6s+P/+rPj//nzI//48eM/8OncP9lUjj/s6uf/+rn3f/q597/1dHJ/3BlWP9LPCv/XE9A/2peUv9rYFP/aV9R/2dbS/9ZTDr/TT8s/3BmVf+/ubD/8/Ht//n28v/z7+z/8u3p//Lt6P/x7ej/8ezn//Ls5//y7ej/8ezo/+/r6P/v7Oj/8e7q/+fl4P97bln/Yk0t/kY2Hl9INhsAWkg0tM++nf/y2qP/79WY/+3Tlv/t05T/7tKT/+3Rkf/s0JD/69CQ/+vPkv/ozZH/4MSJ/491TP+Iemv/6OTc/+ro4P/b2NH/bmRX/1RGN/9pXVH/bWNY/3htYf9+c2b/gHVm/391Zf95bl//aFxL/1BFM/9QQy//f3Zl/8rGvv/x8Ov/9/Xx//Pw7P/y7ur/8ezo//Lt6P/z7un/8e3p//Ht6P/x7en/9PHu/7Osov96Yz//i25D/0YyG2VJNBkAW0gztNHAoP/03Kb/8Naa/+7Vl//t1Zb/79SW/+7TlP/t0pL/7dGS/+3RlP/pzZP/zbF7/25aP//NxLj/7uri/+ro4v+If3L/U0Y3/25jV/9zaFz/f3Nl/3FjUv9YSjn/VUY1/09BMf9XSTr/em1f/3ZsXf9iV0j/VUk4/05ALf98b2H/xMC3//Lx7f/49vL/9PDt//Pu6//y7ur/8+3q//Tt6v/07+z/5eHd/3hnUf+ylWD/lHVH/0UwG2dJMhoAXEkzstHCof/03af/8daa/+7WmP/u1pj/79aY/+7Vlv/v1Jb/79OV/+3Rlv/ozZP/p49h/31uW//s5tz/8ezk/8bAt/9YSTn/b2NX/3RpXv90ZFX/Wkk3/1ZHNf9gU0P/ZFhJ/2daS/9XSjv/Sj0t/3xvX/96bV//aV5R/1RFNf9TQzD/aF1M/310Zf/Iw7v/9fPv//j28v/08e3/9PDs//Xv7P/49fL/q6Sa/31mQP/bu3z/k3RF/0QyHGdJNBwAWkgystLCov/13qn/8dic//DXmv/x1pn/8NaY/+/WmP/w1Zj/8NSX/+3Slv/nzJL/h3FL/56Uhv/z7eb/8Ovk/4uBc/9fUEL/eW1h/3ZpWv9VRDH/TT8t/2ZaTP9XTD7/Sj8v/1dKO/9yZ1n/XVJG/0s+Lv+BdGX/cGVZ/2VYSv9aTDn/u7Kk/5WMe/9tYU7/hXxs/8vIv//19PD/+vn1//n39P/W0s7/bl1H/7icZ//lxoT/k3ND/0UyHWhKNR0AWUYys9HBov/14Kz/89qg//PZnP/z15r/8taZ//LXmv/w15n/79WX/+3Ul//lypH/emZE/7u0qv/z7un/6OPb/25hUP9wZFb/fHFk/2pbSv9HNyP/YVRD/1lMPf89MCD/PS4d/z4vHf9SRTb/a2BT/01BMv9bTj//em5h/3BjVf9TRDL/ta2f/+Te0f/JwLD/WEo0/1ZHMP+HfW3/sq6j/6Odk/9pWkn/l35S/+PGh//lx4b/knJD/0YxHmlJMhsAWUYytNHBov/24a7/89yi//Pbnf/z2Zv/8tmb//PZm//x2Jr/79eZ/+3WmP/ix47/d2VF/8zGvv/z7+r/3dfO/2lcSv99cmT/fXFj/1dINv9VRzb/b2JS/0k8LP87Lh3/PC4c/z4vHv8+MB//XlNE/2RYSf9SRDP/dWpb/3NmWP9XRzT/pZyO/+zo3f/f2s3/bF1K/5h/T/+bg1H/gm1D/4RvR/+ymWb/5MeG/+fLi//lyIf/kHFC/0UxHWpJMRoAW0gztNLDpf/447D/896j//Tdn//0253/89qc//PanP/z2Zv/8dia/+/Xmf/hyI7/d2RG/9DKw//08Ov/2NPI/2tdTP+EeWv/fXFk/1NEM/9rXk//eGxd/0g7KP+De23/Z15Q/zotG/8+Lx7/Wk5A/21gUf9PQS3/bWFS/3VoWf9YSDX/oZeJ/+3r4f/k4NX/cWRR/66TYf/hxIL/4sWE/+XJiP/qzYv/6c2M/+nOjv/nyor/j3FC/0UxHGlKMxwAWkgztdLDpv/45bL/9uCl//beo//13aD/9Nyf//Tcnv/z253/8tmc//HXnP/mzJP/emVE/8jCuf/28u3/4t3T/2xfTv+FeWr/gHVn/1pMO/9cUD//gHVm/2VaSP+clYn/gntv/zosG/9GNyf/ZVhK/1dKOv9KOyn/c2VW/3hpWv9WRzT/sKeb/+7q4v/h39T/bmFM/7mfa//myYr/6MyM/+rNjf/rz47/69CP/+vQkP/pzIz/kHJD/0UwHGlLMxwAWUcxtNHDp//45rP/9uGn//fgpf/336P/9d2h//TdoP/z3Z//89ue//LYnf/t1Jr/h3FJ/7Wtof/38+7/7+ri/3twX/+BdGL/h3tt/3JkVP9JOSb/hXtu/8/Mw/9lWk3/SD0u/09BMf9kVUb/YFJC/0EyIv9dTz//e21f/3doWf9bTDv/zse8/+/r4//Y1cn/aFlB/8yxev/rz4//69CQ/+zRkf/s0ZH/7NKR/+3Sk//szo//k3NG/0UxHWhKMhsAWUYvtdLDp//65rX/+OOo//jipf/54aX/99+j//Xfof/03qH/89yg//Lan//z2p//pY5f/5aNfP/29PD/9fHs/6acj/9tX03/koV2/4R5bP9kUz//UDwo/39xY/+CdWj/cGRW/2NVRf9bTDv/RDUk/1NFNP91aVr/fXFj/21eTv96bV3/6eLb//Lt5v+8tav/cF4+/+HHi//u0pP/7tOT/+/UlP/v1JT/79WT//DUlv/u0ZH/lXZI/0QwHGhJMBoAV0Qut9LDp///6rv/++at//vlqf/746j/+uKn//njpv/44qb/9+Cl//Xepf/24Kb/0ruG/4BwV//t6uX/9vPv/9/a0f9uYU7/in1t/4yBdf+Gemz/a1lE/004Iv9NOyb/UD8t/0g4Jf9DNCH/WUk5/3dqXP98cGP/gXVm/2BRP/+7sKT/8Ovl//Lu6f+Qh3v/moRb//DYmf/x15n/8tiZ//PZmf/z2Zr/8tmZ//LYmv/y1Zb/lXhM/0EvG2dGMRkATz4qubGlj//Vx6v/0sSi/9PEof/TxKD/0sOg/9LEoP/SxJ//0cSf/8/Cnv/NwZ3/x7qV/3FgRv/BurH/+fb0//Xy7v+7sKH/alhF/5WJe/+Og3b/iHts/4BxXv9zZE//altH/2tcSP90ZlT/f3Fi/4B1Z/+Femr/altG/5GDcv/q49v/8Ozn/9zZ0/9nWUf/sJ56/869lf/JupP/yruU/8u8l//MvZn/zL2Y/8u7lP/LuI7/f2lI/z4vGmRDMhkARTYkuFhKN/9iUT3/YlI+/2NSPv9jUj3/YlE8/2JQPP9iUDv/YlE7/2JRO/9jUTv/Y1I7/1lHL/93aVb/7Ojk//bz8f/y7uj/saST/2paR/+Qg3L/mI19/42Dcv+Jfm7/iHxs/4d7a/+He2z/in9y/4h9bf9oWEP/kIFw/+Xe1//x6+f/8e7q/5OKgP9SQS//Xk47/2BPPP9fTTr/X046/2FQO/9jUTz/YlA8/2BPO/9gTzv/UEAr/0E0IGFCMx4ATkExubavo//Y0cf/1czC/9PKwP/UysH/08nA/9PJv//SyL7/08m+/9PJv//UysD/1MvA/9PJvf+FdmH/nJKE//f18f/18/D/8+7o/7uyov9yZlL/cWNR/4p9a/+PhXT/kYV3/4+DdP+HfGv/cmVR/2VWP/+dkID/5+HZ//Lt6P/08O3/t7Kp/2pfTP/FvK7/0sq//9HIvf/RyL3/0sm+/9PKv//Tyb7/0si9/9LJv//WzMH/inxq/z4xIGlAMR4AUEU1us3Kwv/49fH/9O/r//Pv6v/z7+v/8+7q//Tu6f/07un/8+7p//Pu6f/x7uj/8O3p//Lv6//a08j/dmdS/62lmf/39fH/9vPw//Xy7f/j3dT/tKmZ/4+AbP98a1j/cmNS/3JmVP99cWD/n5OD/9PKvv/x6+T/8u3p//Xy7v/Fvrf/bV1M/7y0pv/w7ef/8ezm//Hq5v/y6+f/9O3o//Pt5//w6+b/7+rl/+7r5f/x7OX/lop6/z4xIW5BMh8AUUU2tM3Iwf/49PH/8+7r//Lt6v/x7en/8e3p//Ht6P/y7en/8e7p//Dt6f/w7ej/8O3p//Dt6f/x7+z/1s7D/3RmUv+elYj/7+zo//j18v/28u7/9/Pt//Tu5//t5t3/5+DW/+ji2f/v6eL/9O/q//Tw6//18ez/8u/s/7Suo/9tXk3/ua+i/+/r5P/u6+T/8Ork//Dq5v/n4tz/1tDJ/97a0v/t6ub/7enl/+7q5f/v6+T/kYZ3/zwwIGhCNCMATD4tmsC7sf/59/P/9O/s//Lt6v/y7er/8e3q//Lt6v/y7er/8u3q//Ht6v/x7er/8e7q//Du6f/w7en/8/Dt/9nRxv9/cV7/fnNk/8vGvv/y8O3/+PXy//nz7//48+7/+PLu//jx7v/28e3/9vPv//Px7v/a1tH/j4Z6/25gUP+/tav/7+vn/+/s5f/u6+T/7uzk/+rl3v+LfWv/ZVA0/3BeRP/Qy8L/8e3q/+/r5v/u6+P/g3lr+zgrHFJBMyQAQTEdXpqSg/f6+PT/9PHt//Pu6//07er/9O3q//Pu6v/y7er/8u3q//Pu6v/z7uv/8u7q//Hu6v/y7ur/8+/s//Tw7P/p49z/sqmd/3ltXf9/dGX/qKCV/83HwP/d2dT/5ODb/+Dc1v/Py8b/saqj/4p/cv91Z1P/mI19/9rTy//w7Or/7+zo//Ds5//v7Ob/7+3n/+bg2P92Ykz/X0Un/15GKP++s6f/9PDs//Hu6f/k4dr/Z1tL5jQnFytAMyMAOSsXGWNXQsfX08z/+Pbz//Tw7P/07+z/9O7r//Pv6v/z7+v/9PDr//Tw6//18Ov/9O/r//Pv6v/z7+v/8+/r//Pu6v/z7uv/9e/t/+bg2P+8s6X/k4Vz/3prWP9xZFL/cWRS/29hT/9wY1L/gnVj/6ufjv/Z0MT/8Ozl//Ht6f/v7Oj/8ezn//Lt5//x7ej/8O3o//Ht5//Tybv/r6KR/7Somf/p4dr/8+7p//bz7/+wqqL/STosnzcqGQVDNykASDccAEM1H1F+dGPt5eLc//n39P/18vD/9vDt//fw7f/38O3/9vHt//Xx7f/28e3/9/Ds//bw6//28Ov/9e/r//Tv6v/z7ur/8e3p//Hu6v/08ez/8+7o/+rk2//f2M//29PJ/9vTyv/k3NT/8Ojh//Tu6f/z7en/8uzn//Ls5//x7Ob/8u3n//Pu6f/z7ur/8+7q//Tv6v/38e3/+fLu//ny7v/48u3/9/Tx/8vHwP9eU0XXOC0eLz0yIwBXVEkATDwtAEUyJwNJOylmc2dX57u1qv/l4tz/7enl/+7q5//v6+j/7+vo/+/r6P/v6+f/7+vn//Ds5//w7ef/9PHr//Tx7f/z7ur/8u7p//Dt6P/x7en/8u7p//Pv6f/z7un/8+/q//Pu6f/y7Oj/8evn//Hr5v/x6+b/8ezn//Hs5v/z7ur/8Ozn/+7p5f/v6eX/7ejj/+zo4//s6OP/7enk/+3p5f/f29f/qKKa/11SRNY8MB9CPi0YAEA1KQAAAAAAAAAAAEA2LQA9NzUCPzAgOE8+K55jU0L0dmdY/3hnV/95aVb/emlW/3tqV/97a1j/emtY/3lqV/95bFj/gXZl/9LOxv/38+//9O/r//Lv6v/x7un/8O3o/+/s6P/v7Of/7+zo/+/r6P/u6+f/7urm/+7q5v/v6+f/7+zn//Hv6v/NycL/em9h729gUepzY1T+e2xd/3trXP96alz/fGxd/3psW/9dTj3xQTQkjjgqGSgAAAAAQTgsAAAAAAAAAAAAAAAAAAAAAAAAAAAARDcmADUoFxFXSTbJr6OT/72ypP+6sKD/ubCf/7qxn/+7sKD/uq+g/7itnv+Rg3D/Rjch3390Y/Lv6ub/9PDt//Lu6v/w7en/7+zo/+/s6P/v7Oj/7+zo/+/s6P/u6+f/7uvn/+7r5//u6+f/7Ozp/+zs6f99dGj0NSQUXDUkEkxoWUnwv7ar/8S9s//BurD/wruw/6KZiv9MPSm6MyQYCj8xIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATkEvAHecYQBIOilkYlVE2nJnWOtzZ1jsc2dY7HNnWOxzZlfsc2ZX7XRmVuxcTjzQRDclS0k8KZqkmoz/9fDs//Tw7f/y7+v/8u7r//Hu6v/w7en/8O3p//Ht6f/x7en/8O3p/+/s6P/x7uv/8vLw/6WgmP9KPS6hOywfCkA3KQpLPjCTZVhL5GtgUulrYFHpbGBS6F1RQddGOCdWRTYfAE5CNgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4xJgA+MigDOCgYHDcoFy05KRkvNygXLjcnFS44KBUvOikWMDooFS0/LRwYDgAAADguHhxPQjCvm5GE/ebi3P/59vT/+PXz//bz8f/18e//9fHv//bw7//28O3/9vPw//f18//o5eL/m5WM/kxCMrc4LBwfPDAhADcrIAA6LyYJNScZIzgpGio6KxwrNygZKDgoGhpGOS0CQzcqAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAUkdaADktHQA4LSAURjcnfG1hUt2ck4n9vrix/9bSzf/e3Nj/4+Dd/+He2v/Z1tL/xcC7/5+Zkf5vZFjkRDkphzgvHRk5LxwAOzgxAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6LSIAOCwmAjosHCNCNSRmTD8tpldLOcNdUkHNYVZG0l5TQ9FXTD3JSz4xqzwwInM4KRosPCsgAzsqHwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENhSAAvFQUAODAbAzUpFwsyJBMRMiEQFDQmFBQ2JxUONigbBDYlAAA7MT0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA////////AAD////4P/8AAP////AP/wAA////8AP/AAD////gAP8AAP///8AAPwAA////wAAPAADwAAAAAAMAAMAAAAAAAQAAwAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAIAAAAAAAwAAgAAAAAAHAADAAAAAAA8AAPAAAAAAHwAA+AAAAAA/AAD4AQAAYD8AAP//gAD//wAA///AAf//AAD///gP//8AAP///////wAAKAAAAEAAAACAAAAAAQAgAAAAAAAAQAAAwg4AAMIOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALzI8AC8yPAExMDYCLDdAACw2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADo4JgA4LSEAOTAjDTcsH1I7LR2TPi8cpDstHIM4LiA2NzQsAzcxJwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEZFOgA6KiMAOi0mHDwsHKVSPiL3dls0/4FlOP9rUi3/RzYg6DwuHo08LR8rOzMpAzsvIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4LiIANS4jDzwsHaZmSiz/qIRI/7uTTv+5kEr/rIRE/3pdM/9KNiD+Pi8b4josGow2KB4qLScfAjIoHQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA3LyMAUiMDADUqGm9YQif6r4xO/8CYUf+7kkz/uY9K/6+HRv+Rbjv/jXFA/5J3Qv9wVy7/SDQa4DorF4A3LB8fPFKDADkxLAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPi4dADssHS9CMhrdlXZD/8OdVf++l07/vJNN/7ySTP+8l1j/z65x/+PEf//pyX//27px/62LT/9tVCr9RTQc0jkqGmw5KyEVSSoKACgpNAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQDMlAD00Kwg9LBmgcFQt/8OcVv/Em1P/vpZP/76TTP/DmlX/3L5///DTkf/u0Yn/7c6F/+3Ogv/ry3//2bZu/6CASP9gRyP7Qy8XxDoqF184LRwTMBcAAD06NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTYqADwtGQA8LRxPUT0d8q2MS//LoVb/xZtS/7+VTv/AlEz/2rh0//DVlP/v0oz/7tCI/+7Ph//tzYb/68yE/+vMhP/nyID/zKtn/5V1QP9hRyL5RTEWwjgqGFw1KiARLyYUADotJgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEEyHgA/MR0TQTEevox3Uf/KpVr/xZ1T/8OaUv/Blkz/0ati/+/Vlf/x1I//79GK/+/Riv/u0In/7c+I/+zOh//rzYb/682G/+rNhv/nx3//zKxp/5Z2P/9dQyL4PywYvzgoGVgzKSIOOywcACMjLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABHTFIANywfADkwJgc5LB0uOCkaWTcoG3E6Kh14OykbejsqGXk7Kxh3OyoXdjwqGHg6Kxt4OCsceDorHXc8LR14PS4eeTkrG3k2Kxp5NioceDgsHnU7Lh90Oy4feDouH3o6Lh57OSwbejgqG3k5Kxx7OSsbfDcpGXo5Khl0Py0WmGFSPvnNw6//18Wd/8qoaf/HnFH/zKNY/+jPi//y2Zf/8NSN/+7Si//u0ov/79KL/+7Riv/t0In/7c+I/+zOh//qzob/6s2G/+vOif/ox4H/yadi/4xtOv9UPR33OCkWuDUnGk07LiYJOSoeAD+W/wAAAAAAAAAAAAAAAAA/LR4AGx4NADkrHCo7KRmdRzMa6FpEJPxnUC7/aVAv/2lPLv9pUC3/alEu/2lQLv9pUC7/aVAv/2lRMf9rUzL/alMy/2lSMP9nUS//Z1Ev/2dRMP9oUjL/aFIx/2ZPLv9lTyz/Zk8s/2ZPLP9mTSv/ZU0t/2NLLf9fSCv/Uz0h/0c1H/+kmIj/2tHE/9jPwP/Wx6z/z7B5/+DDfP/03Zz/89eT//DVj//v0o3/79KM/+7SjP/w0ov/79GJ/+/Rif/u0Ij/7tCJ/+3PiP/tz4j/7M6G/+zNhv/kxHz/wqFe/4FlNf9QOx/yPiwZozcqHS4AAAAAOjQoAAAAAAA+NCkANwAAADsnGkRGMhnUclgx/62KUv/Jp2j/0rJw/9Oycf/TsnH/1LNy/9Sycv/TsXH/0rFw/9KxcP/SsXD/07Jw/9OycP/SsHD/0a9v/9GvcP/Qrm//0K5w/9CucP/PrG3/zqxs/8+sbf/Nqmv/yKVl/8CdYP+3lFr/q4hQ/2lMJv91Y0//0ce4/9PLvf/Uyrr/0si4/9vRv//w58n/896o//PXlf/z1ZP/8tSQ/+/Ujv/v043/8dOM//HSi//w0ov/8NKK//DSi//v0Yr/7tCJ/+3PiP/szof/7M6H/+zNh//lxHz/w6Fe/4FlN/9IMhrXOSoZPTooDwBNREEAPCUPAD0qHTxMNh3cjHFD/9Kvb//jwH7/4cB9/9+/fP/fv3z/4sB+/+LAfv/iwH7/4b99/+G/ff/iwHz/4sB8/+LAfP/iwX3/4sB9/+G/ff/fvn7/3r19/968fP/du3z/27p8/9m5ev/YuHn/1bR1/82sbP/Fo2T/u5da/5NzPf9VPyP/s6iX/9PMvf/Px7j/z8e2/9LKuf/p5dv/+PXv//fw3//15b3/79qe//DWkf/w1I//8dSP//DUjv/w043/8NKN//DSjf/x04z/8dOK//DTiv/v0or/7dCJ/+zPiP/uz4f/7NCH/+/Rhv/kxXr/kXdD/0EuGsI2LSEbPS4gADwtIhxDLhrFjG5B/9q4d//kw4H/4sKA/+DAfv/gwH7/4MB+/+LAgP/iwYH/4sGB/+LCgP/iwYD/4sF+/+PBff/jwX3/4sJ9/+LCf//hwoD/4MGB/96/gP/dvX7/2rt9/9a4e//StHj/0LJ0/8yrbv/Eo2X/u5pb/6uITv9kSSP/hndh/9TMu//Px7j/zsS0/8zEsv/c1sn/9PLt//Xy7f/28Oz/9vDp//Tr1//w4Lb/8NiZ//HVkv/x1ZH/79WP/+/Vjv/w1I//8dWM//DVi//w1Ir/79OM/+7Si//t0Yr/7tGJ/+7RiP/t0Yf/7tSI/9nAff9dSiv6OCsdcD0PAABAKxt5aE0q/8+xcv/nx4X/5MSC/+PDgv/jw4H/4sKA/+LCgP/iwoH/48OC/+PDgv/kxIP/48SC/+PEf//jxH3/5cR8/+TFff/jxH//4cOB/+DCgf/ev4D/27x+/9i5fP/Ss3b/zK1w/8enaf/DoWP/vJpd/7WSVf98XjT/XUo0/8i8q//WzLv/z8a1/83Esv/RyLj/7Ojg//Xz7//07+v/8+/q//Lu6f/y7ur/8+/m//Pr1f/w4LT/8dib//DVkv/x14//8daQ//DVjv/w1Iz/8NWL/+/TjP/v043/79KN/+7SjP/u0Yv/7dKK/+3TiP/u2ZP/g3RP/zosHLJALycZSjMdy6eLWv/qzY3/5siH/+TGhf/lxYT/5MSC/+PEgv/kxYP/5cWE/+TEg//kxIP/5MSD/+TFg//jxYH/5MWA/+XGf//kxH//48OB/+HCgv/fwIH/3L1//9e4e//QsHT/yalr/8ekZf/DoGH/vJpc/7CRVf+Xe0j/UTsg/5qMfv/Z0MD/0ce2/87Esv/MxLP/39rP//Xy7f/07+v/8u7q//Ht6P/w7Oj/8ezo//Ls6P/y7un/8+/m//Pq0//y4LX/8NmY//LWkP/y1pH/8dWP//HWjf/w1ov/8NWM//DUjv/v043/79KN/+/Tjf/u1Iv/8d2b/5GFY/88LRrAPy4eSF5JK/HWv4n/6s+S/+jJif/mx4f/5cWF/+TFhP/kxoX/5ceF/+XGhf/kxoX/5MaF/+TFhP/kxoX/5caE/+XFg//kxYP/48WC/+HDgv/gwYL/3b+A/9e3e//OrnH/yKZp/8OiZf+wkVn/j3RF/21XMf9VQyT/Rjcc/00/K//CuKn/1My8/87Ftv/MxLL/1s/A//Du5//28ez/9O7q//Lu6f/x7ej/8Ozn//Ds6P/x7Of/8uzn//Ht6P/w7un/9O/n//Pr0//x4LD/8deW//LWkf/x1pD/8NaP//DVjv/x1I7/8dOP/+/Ujv/w1o//79eM/+3bn/+AdFn/PC0brD8wGm94ZEX869Sj/+rNj//oyor/5siJ/+XHh//lx4f/5seH/+bHh//myIf/5ciH/+XHhv/lx4b/5ceG/+XHhv/lx4X/5caF/+LFhf/gwoT/3b+C/9a4fP/PrnH/x6Vn/7GSWf98ZDv/Tzwj/0w9KP9oWUb/iHpk/2xfSP9IPCr/wLem/9PKuf/Qxrb/0Mi4/+jj2//39PH/9O/q//Lu6f/x7ej/8uzn//Hs5//v7Of/8Ozo//Ls6P/x7ej/8O3o//Ht6P/y7ur/9e/k//Ppy//w3av/8NeW//DWkf/z1o//8tWQ//LVkf/x1pD/8diQ//HYkP/az5z/X1E8+UAvIWtBMR6Cj31g//Hdr//pzY7/6MyN/+fLi//myYr/58iJ/+fIif/nyYn/58mI/+fIh//myIf/5siH/+bIh//myIf/5siH/+THh//hxIb/3cCE/9e4ff/Or3L/wKFk/5BzRf9YQSX/Wkw5/4uBb/+8sqL/2M6//97Vxv+rn47/PzQi/6yikP/UzLn/1cm1/97VxP/18+//9fLu//Tv6v/y7un/8u3o//Ps5//x7Of/7+zo/+/s6P/w7Oj/7+zn/+/r5v/w7Ob/8ezn//Ht6P/07+r/9e/i//Poy//w3qz/79aU//LVkP/z1pH/8teR//LZj//0353/sKWG/0k5Js5BMiceQzIhjJaGav/x37P/6c6Q/+rNkP/pzI7/58qM/+fKiv/ny4r/6MuK/+nKif/oyYj/58mI/+fJiP/nyYj/58mI/+XJif/jx4j/4MKH/9m8gf/Rsnb/vZ9l/3ddNf9NOiX/gHNi/8rCtP/k3tD/5uDV/+Ld0v/d2M3/zcW4/15TQ/93a1j/1s65/9nKsP/p3Mf/+vj1//Xx7v/y7ur/8u3p//Ps5//y7Of/8ezn//Ds5//v7Of/7+zn/+3r5v/v6+b/8ezm//Ls5//x7Oj/8e3o//Lu6f/z7+r/9fDi//Poyf/w3qb/8deT//PYkP/y2pL/5Nmo/29iTP5CMyF0RyoPAEQzIpKXh2z/8+G1/+vQkv/rz5L/6s2Q/+jMjv/oy43/58uL/+jMi//py4v/6MqK/+jKif/oyon/6MqJ/+fKiv/lyYr/4saK/92/hv/Vtn3/wqVs/3NaOP9TQi3/oJaG/93Wyv/m4df/5N/W/+Pe1//k4tr/5uTc/+Pf1v+rpJj/ST0s/5+Vgf/e0rv/6t/M//r59//08fD/8+/t//Lt6v/y7ej/8uzn//Ls5//y7Of/8uzn//Hs5//w7Of/8Ozn//Hs5//x6+b/8Ozn//Ds5//w7Of/8e3o//Lu6v/x8Or/9u/i//PnyP/x3aT/8N+g/6qhhP9HOibWRDUoIEU3KQBGNSORmolt//Tjtv/u0pb/7dGU/+vPkv/pzZD/6MyO/+jLjP/ozIz/6c2N/+jMjP/oy4z/6MqL/+jKi//nyov/5cmM/+DEiv/Zu4H/yqxx/3piPP9XRzX/s6mb/+Te1P/m4dn/49/Y/+fl3v/m497/ycO8/5SMgf9uY1X/V0s7/0EyIP9GNiT/em5e/8K6r//19PH/+fj3//Tx8P/z8O3/8u7q//Lt6P/y7Oj/8+vo//Pr5//z7Of/8uzn//Ls5//x7Of/8evm//Hs5//w7Of/7+zn//Ds6P/w7ef/8O3o//Dt6v/z7+r/9vDi/+DZwf9iV0D/QTEhqkE0LARFNioARzUjkJyLb//047j/7tOX/+7Slf/s0JP/686R/+vOkf/qzo//6s+O/+rOjv/qzo7/6c2N/+nNjf/ozIz/58uN/+TIjv/dwYf/1LV6/41ySf9SQy3/sqiZ/+nj2f/n4tn/5OHa/+ro4v/IxLz/dmxg/0k7Kv9FNSX/T0Ew/1hLOv9dT0D/WUs7/0g6KP9KPSr/hn9u/97c1f/6+vj/+Pbz//Tx7f/z7+z/8+3q//Hs6f/x7Oj/8uzo//Ls5//y7Of/8uzn//Ls5//y7Of/8ezn//Ds5//w6+j/7+zo/+/s6P/w7On/8e3q//Xz8P+hmZD/RDYh/0Q0ILdEMyUHRDQmAEY1IpCci2//9OO4/+/UmP/v05f/7tKV/+3RlP/t0JP/69CQ/+zQkP/s0JD/68+P/+rPj//qz4//6c6O/+fMjv/kx43/3cCE/62RX/9QPSf/m5KD/+jj2P/o5dv/5+Tb/+zq4/+rpJv/T0Ax/0U1I/9ZSjr/aFtO/21hVP9rYVT/aF5Q/2hcTf9kWEf/Vkk2/0Y3JP9ZTTn/oJiL/+bj3v/7+vf/9/Tw//Tw7P/y7uv/8e3p//Lu6f/y7ej/8e3o//Hs5//y7Of/8uzn//Lt6P/x7ej/8Ovo/+/s6P/v7Oj/8O3p//Pw7f/b2NH/ZFZA/2JOL/9KOB+/PTUmCkM2JgBGNCOUnIpv//Xkuv/v1Jr/79SY/+7Tlv/t0pT/7tKU/+3Skv/t0ZH/7dGR/+zQkP/rz5D/68+Q/+vPkf/mzZD/4seM/9S3ff9uVjb/c2VW/+Hb0//r6N//5+Xc/+7s5f+qpJr/Sjwt/1JEM/9kWEr/al9T/21hV/9vY1j/cWZa/3VrXP93bFz/cWZW/2hcS/9eUT//TUIv/0M2If9iVkL/sKqe/+/s6P/7+vf/9fPv//Pv6//y7ur/8e7q//Ht6f/x7Of/8uzn//Pt6P/z7un/8u7p//Ds6P/w7Oj/8O3p//Hu6f/z8+7/mI6A/2ZRL/+WeUz/TDkdxkI3Jw1HOScARjQjlpyKb//25Lz/8Nac/+/Wmv/u1Zf/7NOV/+3TlP/u05T/7tKT/+3Rkf/s0JD/7NCQ/+zQkv/rz5P/6MyS/+HGiv+wlWP/V0Mr/7+0qP/t6eL/6eXe/+3s5v+7ta3/Sz8w/1dJOf9sYFT/bmRY/25kWf97cWX/iH5w/4R3af9+cmL/fnNj/392Zv+Fe23/e3Bh/2FXSP9aUD//UEQx/0k7J/9tYlH/s6yi/+jn4f/6+fX/9fPw//Pw7f/y7+v/8u3q//Lt6f/y7en/8+7p//Lt6f/x7ej/8u3p//Lt6v/08O3/2dTO/2FQOv+dglT/pYVT/0s1HMhHOCcPSjknAEczIpadjHD/+ee///LYnv/x15v/79aY/+7Vl//u1Zf/79SX/+/Tlf/u05P/7tKT/+3Skv/t0pT/7NCU/+fMkv/cv4b/e2M//3prWv/r5dr/7Ojg/+zp4//e2tP/X1JD/1FENP9tYlb/cGVb/3RoXP+FeWr/fnBe/1VHNf9GNyb/Sjop/0U1JP8/Lx//Rzgo/3VoWf+MgnT/al9R/2ZbTf9gVUb/SDso/0U0IP9mV0j/r6ie/+vr5f/6+vb/9vTw//Tw7f/z7+z/8+7r//Lt6v/z7er/9e7q//Xu6//z7+v/8/Hu/5GEdv9rVDD/0bJ2/6eFUf9MNR3JRjcnD0k4JwBINCKTnYxw//jpwP/x2J7/8deb/+/WmP/u1pf/79aY/+/WmP/v1Zf/7tSV/+/Tlf/v05X/7tKV/+vQlv/nzJH/x6x4/1dEKv+xppj/8u7j/+7p4f/x7uj/nJOG/0s7K/9uYVX/c2he/3RoXf96alv/ZlRC/0o5Jv9cTTv/YFRE/2VaSv9tYFH/YVRE/1JFNf8/MSH/a19P/5WGeP9rX1H/al9S/2FUR/9FNSP/VEQw/1JGNf9lWkr/saqg/+7s6P/7+ff/9vTw//Tx7f/z8Oz/9PDs//Xv7P/17+z/9/Xx/9LOyP9bSjP/pYpZ/+HBgP+lhE//SzYeyUM3Jw9HOCcARjQhk5yMcf/56cL/8dmg//HXm//v1pn/79aY/+/WmP/v1pj/79aY/+7Vl//w1Jf/8NSW/+7Tlv/r0Jb/58yR/6mQY/9VRS//1szC//Hs4//v6+P/39vS/15QQP9fUEL/eGxg/3drXv93aVr/WUg2/0ExHf9dUED/aV1P/2JXSf9YTj//XVJE/3JmWP9rYFP/WE1A/z8zJP92Z1f/in1v/2leUv9sYFP/UEEw/2NWQv+5saH/enBf/09DMP9rYVD/urWo//Hw6v/6+vf/9/Xy//Xy7v/08e3/9fLv//Py8P+JfXH/alMx/9K2ev/kxIP/pYNN/0s3HspCNycQRjgnAEUzIJSci3D/+enD//Lao//x2Z//8dec//LXmv/y1pn/8dWY//HWmf/w15n/8daY//DVl//u05b/69CW/+jMk/+PeFH/Z1tJ/+rk3P/x6uT/8+3o/7qzp/9LPCj/cWVZ/3luYv96bV7/allH/0UzIP9RRDL/aFxN/11RQv9EOCn/PTEg/z8xIP9PQTD/eG1f/2tgVf9SRjf/QjQj/4d6bP90aF3/b2NY/2RWRf9KOif/wLeq/9bPw/+5saD/hHhj/0w+Kf9sYlL/trKo//Lx6//8/Pj/+/n1//Lw7f+lnZX/U0Ap/62SYP/myIj/5ceF/6aCTP9MNh/LRTgpEEg5KQBFMiGVm4lv//nqw//y3KX/89ui//Panv/y2Jv/89ea//LWmf/z15r/8tea/+/Xmf/v1pj/7tWX/+zSlv/ny5L/f2lF/350ZP/x7ej/7+rl//Tv6P+dk4T/UUMx/31xZP98cGP/eWxc/1RDMP9ENSH/YlVE/2VYSf9FOCn/Oy8d/z4vHv8/Lx7/Pi4d/0xAMf9wZlj/XlJE/0A1Jf9dUEH/fnJl/3BkV/9uYVH/Rzgm/6Scjf/o49f/4trO/9XNvf9iVD//RzYe/1FBKP9wZVT/npmM/5+Zjf9yaV3/TTwo/5V9Uf/gxYb/5sqK/+XIh/+kgkv/TDUfzEo7LhFNPS0ARDIhlZuJb//56sT/89ym//Pdo//z25//89qc//PZm//y2Zv/89mb//LZm//w2Jr/79eZ/+7XmP/s05f/5MmQ/3VhPf+SiHv/9PHs/+/r5v/x7OX/hnxr/2FTQf+Cdmr/fnJl/25hUf9DMyD/VUc2/3FkVP9ZTTz/PjEi/zwvHv89Lx3/Pi8e/z8wHv89Lx//XVJE/2leUP9YSjr/TD4t/3xxYv9xZVj/cWRV/009Kf+TiXn/7One/+fi1//h283/a15N/3BbNf+wlV//gGpB/2dVMf9kUTD/dWI9/7KaZv/lx4b/58uJ/+fLi//myIj/o4BL/0s0HsxIOiwRSzsrAEYzIpWci3D/+uvF//TeqP/y3qT/89yg//Tbnf/z2pz/89qc//PanP/z2pz/8tmb//DYmv/u15n/7NWY/+PJkP9xXTr/nZOH//Xx7f/w7Ob/7uri/35yYf9vYlH/hHpt/390Z/9nWkn/RjYk/3NmWf9/cmX/UkYz/z8yIf9RRTX/RDko/zotHP89Lx3/Pi4d/1NHOP9tYlX/bF1N/0w9K/9xZVX/c2da/3JlVf9QPyr/in5v/+3q4P/p5tz/5uLW/3RnWP91Xzr/2Lp7/9u+e//Yu3v/2b19/+LGhf/pzIv/58yK/+jMi//ozIz/58mJ/6GAS/9MNR7MSTkqEUs6KQBHNSKWnYtz//vsyP/136n/9d+k//Xeof/13Z//9dye//Tbnf/0253/89qc//PanP/y2Zr/8dia/+/Wmf/kypH/c147/5qPg//18e3/8e3n/+7s4v99c2L/bl9P/4Z8bv+AdWj/aVxM/0c4Jv90aVr/gHRm/1hKNv9VSTb/1tPJ/6OelP87Lx//PS8d/z4uHv9YSz3/cGVX/1tNO/9ENSH/bWBR/3VoWv9zZlX/Tj4q/46DdP/t6uD/6ube/+jk2f9yZ1j/fGVA/9u+gf/hxIT/5MiI/+bKif/oy4r/6c2M/+rOjf/qz4//6s+Q/+jLjP+ggEv/SzUey0Y3JxFINyYARjQhl5uLcv/77cr/9eCq//bgpv/236T/9t6i//XcoP/03J//9Nyf//Tcnv/y253/8tqc//LYnP/w1pv/6c+V/31mP/+MgHD/9fLt//Lu6f/08Oj/kol4/2JTQv+Og3P/gHVo/3VnWP9GNyT/YlVF/35zZv99cWL/U0g3/6Odkv+Nh3z/PC8e/zwuHf9JOir/Z1pL/2VZSf9CMyL/Tj4t/3RnWP95a1z/dGVV/0o6KP+lnI7/7uri/+vn3v/k49b/aF1L/4lySv/hxYf/5smK/+jMjP/pzY3/686O/+vPj//r0JD/69CQ/+vQkf/qzI3/o4FM/0w1HstHNicQSTcnAEUzH5abi3H/+u3L//biq//24af/9+Cm//fgpP/23qL/9d2h//TdoP/03aD/892f//Pbnv/y2Z3/8Ned/+7Um/+QeU3/d2lW//Hv6P/07un/9vHr/7Gomf9TRTL/lYd2/4J2aP+Ddmj/V0g1/0g5Jv95bmH/397X/62onf9HOyz/QTUm/0I2Jf9SQzP/Z1hI/2pcTP9KPCz/Pi8e/2JTQ/96bF7/fG1f/29gT/9NPy3/xr6y/+7q4v/t6eD/3dvP/1lMOP+ehlr/6MyN/+nNjv/rz4//7NCQ/+zRkf/s0ZH/69GQ/+zRkf/t0ZP/7M6O/6aDT/9MNR7LRzoqEEs7KQBFMh2Wm4tx//vtzP/24qz/9+Kp//jipv/44aX/+OCk//ffo//13qH/896g//PdoP/z3J//89uf//HZnv/x2Z3/rpZl/2JUPf/l49z/9fDs//Xx7P/TzMH/VUc0/4p8av+MgHD/hntu/3VoWP9KNyD/Tjwr/6Sbj/+4sKb/fHFk/2VbTf9gUkT/Z1hI/2haSf9SQzL/PS4d/1FDM/90Z1j/e25h/4BxY/9gUUD/aFxL/+Pc0//u6eH/8uzl/8W/tP9RQCr/uqJv/+3Qkf/s0ZH/7dKS/+3Skv/u05P/7tOS/+7Ukv/v1JT/79OW/+7RkP+nhlL/SzQeykI7KRBHPCkARDEdl5qKb//87c3/+eOu//jkqv/44qb/+eKl//nhpf/44KT/9+Cj//bfof/13qH/9Nyh//Pbof/y2qH/89ug/9G5g/9fTC7/ysa8//f28f/08e3/7unh/4J3Z/9iVEH/nZGA/4Z6bv+IfXH/c2JO/0w2IP9DLxv/W0o5/3ZoWf93alz/Z1pJ/1dJN/9KOin/PS0c/1FCMv9zZlf/e29h/3tvYv+Ac2P/UEAu/6OYiv/w6uT/7uji//Tv6v+ck4f/Xksu/9jAhv/t05X/7tSU/+/UlP/w1ZX/8NWV//DVlf/w1pT/8NWV//DUl//v0pL/qYlV/0s1HspCOSgQSDspAEQxHZqYiG3//e7O//vksP/65Kv/+eSo//nipv/54aX/+OCk//fgpP/34aT/9uCk//Xfo//03aL/89yi//Ldov/t1p3/fWY//52Shf/6+fX/9PLt//Xy7v/Kwrb/Vkg1/4h6af+UiHz/h3xw/4l+cP95aVX/W0Uv/0gzHP9CMBr/QzIf/0IyH/89Lhv/QjMg/1lKOf92aVr/fXJj/3pvYv+He23/aFpI/2dYRv/d1Mr/8Ovl/+7q5f/s6eT/a2BT/4x1UP/t1Jb/7dWX/+/Wl//w1pf/8deX//HXl//x15f/8NeW//DWlv/x1pf/8dSU/6iJV/9INR3JQDcqD0U4KgBALxyckIFr//Lp0v/v4cH/7uC8/+7guv/v4Lr/7uC5/+3fuf/t4Ln/7OC4/+zguP/s4Lj/69+4/+ret//n3LX/6t20/6eXdf9nWEX/6eXg//f08v/08e7/8+7m/6CTgP9VQi7/mYx+/5OIe/+GfG//in1v/4d2Zf94aFT/bF1H/2VVP/9jUz3/Z1hD/3NlUv9/cWL/gHRm/3xyZP+GfGz/eWtY/1dGMP+3rJ3/7+ni/+7p5P/y8Oz/xcC4/1VHMv/Ar4j/6tqs/+bWq//k1qv/5des/+bYrv/n2bH/6Nqy/+fZsf/n2K7/6Nis/+jVp/+ehl//QzIbx0A2Kg5CNikAQTMhm1JDL/9mWUX/aVhE/2lZRP9qWkT/bFtE/2xbRP9rW0P/a1pD/2xaQ/9sWkP/a1tD/2tbQ/9qWkL/aVlB/2lZQP9fTzX/RjUc/6adj//6+PX/9fHu//Xx7//q49n/koJs/11MOf+bjX3/n5SF/4t/cP+He2z/iX1s/4p9bP+Ie2v/h3pr/4Z6av+EeGn/gHRn/4N4a/+Rh3f/eWpW/1pIM/+rn5D/7ubf//Dq5f/v7Of/7Orm/3RoXP9EMh7/YlI7/2hXQP9mVD//ZVI9/2VTPf9mVD7/Z1Y//2dXQP9nVj//ZVQ+/2RSO/9kUjn/VUIp/0MzHsJCOSoMRDgqAEIzI5tcTTz/eGpZ/3hoVv95aln/eWlY/3hoV/94aFb/dmZV/3ZmVP92ZlT/dWVT/3ZmU/93ZlP/d2ZT/3ppVf97aVX/emlU/3BeSP9dTDf/1dHK//r39v/18e7/9fLu/+ri1/+Rg3D/UkIu/4ByYf+kmYn/m5KC/46FdP+Ifm//iHts/4d6av+HfGv/i4Bx/5WKfP+Rh3b/ZldD/1hFMP+xo5T/7uji//Dr6P/v6ub/9fPv/6iimP9SQzH/dmhW/3VmVf91ZlX/dmdW/3VmVf92Z1X/d2lW/3pqV/96alf/emlX/3lpWP95aVn/fG1c/2VWQ/9CNSHERTwtDUY8LQA+MSGcj4Z4//Pv6P/s5d3/6+Pb/+nh2f/p4dn/6uLa/+nh2f/p4dn/6eDY/+jg1//p4Nj/6eHY/+rh2f/p4tn/6eLa/+rj2v/g2cz/d2dR/3ZnVv/s6eP/+fbz//Px7v/28u7/7Obc/6+mlP9lWUX/V0g0/3tsWv+Th3T/mY9//5uRg/+bkIL/lop7/4l+bf9rXUn/UEIo/3FhS/+/tKf/7+nj//Ht6P/x7Of/9fLv/8fCvP9TSDX/lIp4/+jh1f/o4df/59/V/+ff1f/n39b/6ODX/+jg2P/o4Nb/59/V/+fe1f/l3tX/5+DY/+vj2P+qnIv/RDYkzUU5LRJHOy8APzMjnpGKe//7+ff/8+/r//Lu6f/y7un/8u3p//Lt6v/y7en/8u3o//Pt5//z7ef/8uzn//Lt6P/y7Of/8Ozm/+/s5//v6+j/8e/q/9HJuv9jUTv/h3xs//Hv6f/39vL/8/Ht//Xy7v/08er/3tjM/6yhjv9/bln/Z1Y//11LNv9YRzb/Vkg2/1dKN/9fUj//f3Fe/7aqmv/k3dL/8u3n//Hs5//x7Oj/9vPw/9POyP9jUkL/fXBe/+Hc0f/w7ef/8Ovl//Dp5f/w6eX/8erl//Hq5f/x6uX/8Orl/+/q5f/v6eT/7enj/+3q5P/y7OT/raCR/0U3JtFGOi4USDswAEAyJJuSi37/+/j2//Tu6//y7er/8u3q//Lt6f/x7un/8e7p//Ht6P/y7ej/8u7p//Lu6f/x7ej/8e3o//Ds6P/v7Oj/7+zo/+/s6f/y7+r/y8Gy/2FRO/+FeWr/6efg//r49P/08e//9PHt//by7f/38uv/8erg/+Pbzv/Uybv/yL2v/8e+r//Sy73/4NrP/+/p4f/28Ov/9fDq//Lt5//y7ur/9/Xw/8vHv/9kVUX/fGxZ/97WzP/v7Ob/7erl//Dq5P/v6eT/7+nl//Ls6f/07+v/9PDq//Hs5//t6eT/7unl/+7q5P/u6uT/8ezl/6mekP9DNiXOQzkuEkQ6LgA/MSOPkId5//r59v/08e3/9O/s//Lt6v/y7er/8e3p//Dt6f/x7en/8ezp//Lt6v/x7er/8O3p//Dt6f/w7en/8O3p//Dt6f/w7en/7u3q//Tw7P/KwbH/YFA6/3BiUP/SzcX/+vn1//j08f/18O3/9PDr//Xw6//28ez/9/Lt//jz7v/48u3/9vDs//Tv6//y7ur/8e7o//Lv6v/28/D/8vDt/66nnf9XSDb/fm9e/9zWzv/w7ef/7uvj/+7r4//v6+P/8Orl//Ds5v/Kw7r/pp6S/6igk//SzsP/7u3q/+3q5v/u6uX/7uvl//Ht5f+hl4r/QjQkxEI3Lg1DOC4AQDAgbXxyYvv29vD/9fLu//Tw7f/z7er/8+3q//Lt6v/y7er/8u3q//Lt6v/y7er/8u3q//Lt6v/y7er/8e7q//Hu6v/x7ur/8O3o//Dt6f/w7er/9PDs/9TKvP94aVX/V0o4/52Uif/j4Nv/+fj1//j28//38u7/9vDs//bw6//18Ov/9u/r//Xu6v/z7+r/9fLt//f18f/08/D/0s/I/4B3av9URTT/kIN0/+DZ0v/w7en/7uvm/+/r5P/u6+T/7evk//Dt5v/VzcP/YlA4/1pCJP9cRCP/b19H/+Pf2f/w7On/7+rn/+/r5f/x7ub/j4Z4/z0wIKs/NTIEQzguAEIyIDlfUj/p4uDY//n39P/08e3/8+7r//Pt6v/07er/8+3q//Pu6//y7er/8u3q//Lt6v/y7er/8u3r//Lu6//y7ur/8e7q//Ht6v/y7ur/8+/r//Lv7P/08Ov/5+DY/66mmf9rXk3/X1ND/4uCdP+9t6//49/a//Hv6//29fL/+ff0//n28//08u//6+nl/9fTz/+vqKH/gXZn/11OOf92aFb/vrSo/+vm4P/w7Or/7+vo/+/s5//v7Ob/7uzm/+7s5v/x7uj/x7yw/1Y/J/9oTC3/a08t/11HLf/UzMP/8/Dr//Ds5//w7ef/6+nj/25iUv87Lh18RDMbAEA3LQBIOioLSDolsamilP/8+/j/9fLu//Tw7f/z7+v/9O7r//Tt6v/07uv/8u7q//Pv6v/z7+v/8+/r//Tv6//07+v/9O/r//Pu6v/y7ur/8+/r//Tw7P/z7+v/8+7q//Pu7P/18O3/5d3V/7CnmP95a1f/Xk05/2FRQP9vYlL/fHJk/4d8bv+Femz/d2xe/2VaS/9XSjj/XU46/4V2Xf+7r5//5+HY//Lu6P/u6+n/7+zo//Ds5//x7Of/8ezn//Ds5//v7Of/8O3n/+ni2f+aiXP/bl1F/2lZQv+QgW7/6+Pc//Pv6v/y7uj/9vTw/8fCvP9OPi/pQDMjNEI1JQAAAAAARjYdAEQ3Ik5eUTvx1NDJ//v59//08e3/9PDt//Tv7f/07+v/9O/r//Tv6//08Ov/9PDr//Tw6//18ez/9fDr//Xw6//17+r/8+/r//Tw6//z7+v/8+/q//Pu6f/y7en/8e3q//Lu6//08er/7Ojg/9nOwv+3q5n/mYx6/4d5Z/9+cF3/fW9c/4R3Zf+ZjX3/uK6f/9nPxP/v59//9O/p//Lt5//x7Ob/8ezn//Ds5//x7Ob/8u3m//Lt6P/x7ej/8e3p//Hu6P/y7+n/8uvj/+zj2v/q4df/7+jg//bw6//y7en/8/Dt/+zq5v91bWL/PzIjlUs/MARHOywAAAAAAEk9LQBKQDEGRTciiHRpWPzh3db/+/r3//b08P/08O7/9fDt//fv7P/27+z/9+/s//Xw7P/18Oz/9fDs//bw7P/28Ov/9u/r//bw6v/28Or/9e/q//Xv6v/07+r/8+7q//Ht6f/w7en/8e7p//Lv6v/08ev/9vHr//Tv6P/x7OX/8evj//Dq4//x6+T/9O3n//Xu6f/07en/8uzn//Ls5//y7Of/8uzn//Ls5//x7Ob/8ezm//Lt6P/y7un/8u7p//Pu6f/07un/9O7q//Xu6//27+v/9u/s//fv6//27+v/9/Tx/+/u6/+QiHz/QjYmxjwzJSM+NCUAAAAAAAAAAAAAAAAATT4uAE09LhBJOyiYaVxK+rmyp//u7ef/+fn1//v59v/8+Pf/+/j2//z49//8+Pf//Pj3//z49//8+fb/+/j1//v49P/7+PP/+/jz//r38v/18u3/8+7p//Pu6v/y7un/8e7p//Dt6P/x7un/8u7p//Pu6P/y7uj/8u3o//Pu6P/z7un/8uzo//Hr5//x6+b/8evm//Hr5v/x6+b/8uzn//Ls5//x6+b/8uzo//fz7v/59vL/+/bz//v28//79vP/+vby//r28v/59vP/+fbz//n28//59vX/9PLw/9PPyv98c2j/RTgozEA0JDNAMiAAQjguAAAAAAAAAAAAAAAAAAAAAABHOy8AST40DkM1J2xOPirVbmBO/JGFeP+ckof/oZaM/6OZjv+lm4//ppuQ/6aaj/+mm4//ppuP/6ackP+nnpH/qaGU/6qjlv+3sab/4d/Z//Ty7//07ur/8+/q//Lu6f/x7un/8e7p//Ht6f/w7en/8O3o/+/s5//w7Oj/8Ozo/+/r5//v6+b/7uvm/+7r5v/v6ub/8evn//Ds5//w7eb/8O3p/+rn5P+5sqn/pZuR/6edk/+lmpD/opeL/6GWi/+glYr/oZWL/6SXjP+mnI7/oJaJ/3twYv9PQzTtPjAfnz80JiguHQkAUEhBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEY6MQBKQUIBRzcmHEMyIIFMOyj7cV9O/2tXRP9pVD//aVQ9/2hVPP9pVj3/a1hA/2tYQP9qV0D/ZlM8/2ZTPP9iUDn/Szoj/3RpWP/q6OD/9vLw//Tv7P/08Ov/8+/r//Dt6f/v7Oj/7+zo/+7r5//v7Oj/7+zo/+/s6P/u6+f/7uvn/+3q5v/t6ub/7urn/+/r5//u6+f/7Ovn//Py7/+YkIX/RDQj2D8sGqpCLhvdWkg1/3NjU/9zYVL/cmFR/3FfT/9wXk7/c2JQ/19OOv9BMBzYOiweQD0wIgc/MCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEU5JwBBNSIyWEo47MW7q//c1cj/2NHF/9jRxP/X0cL/19HC/9fRwv/X0MP/2M/D/9XNwf/VzL//lot3/0k7Jd5HOSbYqqGS//n08f/z7uz/8+7r//Ht6f/v7Oj/7+zo/+/s6P/v7Oj/7+zo/+/s6P/v7Oj/7+zo/+/s6P/v7Oj/7+zo/+7r5//t6+f/6+vn/+/x8P/Z1tH/V0s+9T0vIVM9LCAAPzEhgXZpWf/d1sz/4t7W/+Dc1P/e2tL/3trS/97Z0P+GfGr/QTEfpEE2NANFOS0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMPy0ATkEvCkY4J5laTDr4c2hY/3RpW/91alv/dWpb/3ZqW/92aVr/dmla/3ZpWv93alv/c2VV/1FDMfBEOCZmQjUjW1hMOfXPx7z/+vXy//Lu7P/y7ur/8u/r//Lu6v/x7en/8O3p/+/t6P/v7ej/8Ozo//Hs6f/x7en/8O3p/+/t6f/v7Of/7uvo//Ly8P/q6+n/fHRp/0EzJKVIOi8LRDgpAEU6Ky5HOivSYVRH/2tfUf9qX1H/a19Q/2xgUP9oW0z/TD8t5EQ3J0lCNSMAXFFGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAS05YAEI0JgBDNywOQTEhSz8wH3FAMSB4QTEhej8xH3k/MB53Py8deEEwHXlBMR17QTEdekQxHm9GNiVBRzw1Bj85LAc+MiGLZFZD+szFuf/59/L/9vTx//Tx7v/z8O7/8/Dt//Pw7P/y7+v/8+7r//Tu6//07ev/8+3q//Lt6v/w7er/8e/t//j29f/m5OL/gntw/0E1JsdBMyQkQDMjAEQ6MgBZU1QAQDUrJz0wImE+LyBuQTIjcUEyJHE/MSJtPi8gY0I0JTNMQzcDSD4wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABENycARTgqDUAzI4BWSTjuoZiK/+Xh3P/59/X/+fj3//j29f/29PP/9fPy//bz8v/38vH/9/Lx//fz8P/59vP/+vj3//Px7v/Cvbb/amJU/T82JLw+NCQvPjQeAD82LQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEI4LQBCOjEFQTMkSEY3J7dhVEXzh31x/6qjmv/Lx8D/2tjS/+Hf2//m5eD/5uPg/+He2//W1NH/wr24/5iSi/9xZ1v9TD8x3j8zJH1COCcXQTQkAEM8MQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYmRoAD4tGwBIPDENQjUlRUM2JY5HOSfKTkEt5VVJN+9ZTj3zXVJB9VxRQfZXTDz0UEQ27kc6Ldo9MSOzPC8gbkIzJCZQPjgCSjkwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFpTRABfWUwBST8sEkQ4JSZCNSQ0PzIhPT8vHkJAMSBDQTMhP0I0IzNENyscST01CAAAAABUUFMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/////////////////n/////////4D/////////AD////////4AD////////gAH///////8AAH///////gAAH//////+AAAH//////wAAAH/gAAAAAAAAH8AAAAAAAAAPgAAAAAAAAAcAAAAAAAAAAgAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAwAAAAAAAAADgAAAAAAAAAOAAAAAAAAAB8AAAAAAAAAP4AAAAAAAAB/wAAAAAAAAP/wAAAAABAB//AAAAAAEAP/+AAAAAA4A/////AAAH//////+AAA///////+AAH///////+AD/////////////////////////w=="""


def boyut_formatla(bayt):
    if bayt < 1024:
        return f"{bayt} B"
    elif bayt < 1024 * 1024:
        return f"{bayt / 1024:.1f} KB"
    return f"{bayt / (1024 * 1024):.1f} MB"


class SurukleBirakPencere(ctk.CTk, TkinterDnD.DnDWrapper):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.TkdndVersion = TkinterDnD._require(self)


class ExifYokEdiciUygulama:
    def __init__(self, pencere):
        self.pencere = pencere
        self.pencere.title(PROGRAM_ADI)
        self.pencere.geometry("520x480")
        self.pencere.minsize(420, 400)
        ctk.set_appearance_mode("system")
        ctk.set_default_color_theme("blue")

        self.simge_yolu, self.gecici_simge_mi = self.simge_hazirla()
        if self.simge_yolu and os.path.exists(self.simge_yolu):
            try:
                self.pencere.iconbitmap(self.simge_yolu)
                self.pencere.after(200, lambda: self.pencere.iconbitmap(self.simge_yolu))
            except Exception:
                pass

        self.unlem_ico_yolu = ""
        self.unlem_simgesi_hazirla()

        self.dosyalar = []
        self.satir_widgetleri = []
        self.cikti_klasoru = ""
        self.islem_devam_ediyor = False
        self.acilir_menu = None
        self.arayuz_kur()

    def simge_hazirla(self):
        dizinler = [
            getattr(sys, "_MEIPASS", ""),
            os.path.dirname(os.path.abspath(__file__)),
            os.getcwd(),
        ]
        for dizin in dizinler:
            if dizin:
                aday_yol = os.path.join(dizin, "exif_yok_edici_3000.ico")
                if os.path.isfile(aday_yol):
                    return aday_yol, False
        try:
            gecici_dizin = tempfile.gettempdir()
            gecici_yol = os.path.join(gecici_dizin, "exif_yok_edici_simge.ico")
            with open(gecici_yol, "wb") as cikti:
                cikti.write(base64.b64decode(SIMGE_TABAN64))
            return gecici_yol, True
        except Exception:
            return "", False

    def unlem_simgesi_hazirla(self):
        try:
            gorsel = Image.new("RGBA", (64, 64), (0, 0, 0, 0))
            cizim = ImageDraw.Draw(gorsel)
            cizim.ellipse((2, 2, 61, 61), fill="#d32f2f")
            cizim.rounded_rectangle((28, 14, 35, 38), radius=3, fill="white")
            cizim.ellipse((28, 43, 35, 50), fill="white")

            gecici_dizin = tempfile.gettempdir()
            ico_yolu = os.path.join(gecici_dizin, "exif_yok_edici_unlem.ico")
            gorsel.save(ico_yolu, format="ICO", sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])
            self.unlem_ico_yolu = ico_yolu
        except Exception:
            self.unlem_ico_yolu = ""

    def arayuz_kur(self):
        self.ust_cerceve = ctk.CTkFrame(self.pencere)
        self.ust_cerceve.pack(fill="x", padx=10, pady=(10, 0))

        self.gorsel_ekle_btn = ctk.CTkButton(
            self.ust_cerceve,
            text="Görsel Ekle ▾",
            width=130,
            command=self.gorsel_ekle_menusu_goster,
        )
        self.gorsel_ekle_btn.pack(side="left", padx=(5, 3), pady=5)

        self.cikti_sec_btn = ctk.CTkButton(
            self.ust_cerceve,
            text="Çıktı Klasörü Seç",
            width=140,
            command=self.cikti_klasoru_sec,
        )
        self.cikti_sec_btn.pack(side="left", padx=3, pady=5)

        self.tumunu_temizle_btn = ctk.CTkButton(
            self.ust_cerceve,
            text="Tümünü Temizle",
            width=120,
            fg_color="transparent",
            border_width=1,
            border_color=("gray65", "gray45"),
            text_color=("gray15", "gray90"),
            hover_color=("gray85", "gray25"),
            command=self.tumunu_temizle,
        )
        self.tumunu_temizle_btn.pack(side="left", padx=(3, 5), pady=5)

        self.cikti_etiketi = ctk.CTkLabel(
            self.pencere, text="", anchor="w", text_color="gray"
        )
        self.cikti_etiketi.pack(fill="x", padx=15, pady=(2, 0))

        self.liste_cercevesi = ctk.CTkScrollableFrame(self.pencere)
        self.liste_cercevesi.pack(fill="both", expand=True, padx=10, pady=5)

        self.liste_cercevesi._parent_canvas.configure(
            yscrollcommand=self.kaydirma_cubugu_yonet
        )
        self.liste_cercevesi._scrollbar.grid_remove()

        self.birakma_ipucu = ctk.CTkLabel(
            self.liste_cercevesi,
            text="Görselleri buraya sürükleyin\nya da 'Görsel Ekle' düğmesini kullanın",
            text_color="gray",
            font=ctk.CTkFont(size=13),
        )
        self.birakma_ipucu.pack(expand=True, pady=50)

        self.pencere.drop_target_register(DND_FILES)
        self.pencere.dnd_bind("<<DragEnter>>", self.suruklenme_basla)
        self.pencere.dnd_bind("<<DragLeave>>", self.suruklenme_bitti)
        self.pencere.dnd_bind("<<Drop>>", self.dosya_birakildi)

        self.sayac_etiketi = ctk.CTkLabel(self.pencere, text="", anchor="w")
        self.sayac_etiketi.pack(fill="x", padx=15, pady=0)

        self.ilerleme_cercevesi = ctk.CTkFrame(self.pencere, fg_color="transparent")
        self.ilerleme_cercevesi.pack(fill="x", padx=10, pady=(0, 5))

        self.ilerleme_cubugu = ctk.CTkProgressBar(self.ilerleme_cercevesi)
        self.ilerleme_cubugu.pack(fill="x", padx=5, pady=(5, 2))
        self.ilerleme_cubugu.set(0)

        self.ilerleme_etiketi = ctk.CTkLabel(
            self.ilerleme_cercevesi, text="", font=ctk.CTkFont(size=12)
        )
        self.ilerleme_etiketi.pack(pady=(0, 2))

        self.alt_cerceve = ctk.CTkFrame(self.pencere, fg_color="transparent")
        self.alt_cerceve.pack(fill="x", padx=10, pady=(0, 10))
        self.alt_cerceve.grid_columnconfigure(0, weight=1, uniform="kenar")
        self.alt_cerceve.grid_columnconfigure(1, weight=0)
        self.alt_cerceve.grid_columnconfigure(2, weight=1, uniform="kenar")

        self.arindir_btn = ctk.CTkButton(
            self.alt_cerceve,
            text="Arındır",
            width=200,
            height=36,
            font=ctk.CTkFont(size=14, weight="bold"),
            command=self.exif_temizle,
        )
        self.arindir_btn.grid(row=0, column=1)

        self.bilgi_btn = ctk.CTkButton(
            self.alt_cerceve,
            text=f"v{PROGRAM_SURUMU}",
            width=56,
            height=36,
            fg_color="transparent",
            border_width=1,
            border_color=("gray65", "gray45"),
            text_color=("gray15", "gray90"),
            hover_color=("gray85", "gray25"),
            command=self.bilgi_goster,
        )
        self.bilgi_btn.grid(row=0, column=2, sticky="e")

        self.pencere.bind_all("<Button-1>", self.disariya_tiklandi, add="+")
        self.pencere.bind_all("<Escape>", lambda e: self.acilir_menuyu_kapat(), add="+")
        self.pencere.protocol("WM_DELETE_WINDOW", self.kapatildiginda)
        self.sayac_guncelle()

    def kaydirma_cubugu_yonet(self, ilk, son):
        self.liste_cercevesi._scrollbar.set(ilk, son)
        if float(ilk) <= 0.0 and float(son) >= 1.0:
            self.liste_cercevesi._scrollbar.grid_remove()
        else:
            kenar = self.liste_cercevesi._apply_widget_scaling(
                self.liste_cercevesi._parent_frame.cget("corner_radius")
                + self.liste_cercevesi._parent_frame.cget("border_width")
            )
            self.liste_cercevesi._scrollbar.grid(
                row=1, column=1, sticky="nsew", pady=kenar
            )

    def uyari_goster(self, baslik, mesaj):
        uyari = ctk.CTkToplevel(self.pencere)
        uyari.title(baslik)
        uyari.resizable(False, False)
        uyari.transient(self.pencere)
        uyari.grab_set()

        if self.unlem_ico_yolu and os.path.exists(self.unlem_ico_yolu):
            try:
                uyari.iconbitmap(self.unlem_ico_yolu)
                uyari.after(200, lambda: uyari.iconbitmap(self.unlem_ico_yolu))
            except Exception:
                pass

        mesaj_etiketi = ctk.CTkLabel(
            uyari,
            text=mesaj,
            font=ctk.CTkFont(size=13),
            wraplength=300,
            justify="center",
        )
        mesaj_etiketi.pack(padx=25, pady=(18, 10))

        tamam_btn = ctk.CTkButton(
            uyari,
            text="Tamam",
            command=uyari.destroy,
        )
        tamam_btn.pack(pady=(0, 16))
        tamam_btn.focus_set()

        uyari.update_idletasks()
        genislik = max(260, mesaj_etiketi.winfo_reqwidth() + 60, tamam_btn.winfo_reqwidth() + 60)
        yukseklik = mesaj_etiketi.winfo_reqheight() + tamam_btn.winfo_reqheight() + 50
        ana_x = self.pencere.winfo_x()
        ana_y = self.pencere.winfo_y()
        ana_g = self.pencere.winfo_width()
        ana_yuks = self.pencere.winfo_height()
        konum_x = ana_x + max(0, (ana_g - genislik) // 2)
        konum_y = ana_y + max(0, (ana_yuks - yukseklik) // 2)
        uyari.geometry(f"{genislik}x{yukseklik}+{konum_x}+{konum_y}")

    def acilir_menuyu_kapat(self):
        if self.acilir_menu and self.acilir_menu.winfo_exists():
            self.acilir_menu.destroy()
            self.acilir_menu = None

    def gorsel_ekle_menusu_goster(self):
        if self.acilir_menu and self.acilir_menu.winfo_exists():
            self.acilir_menuyu_kapat()
            return

        self.acilir_menu = ctk.CTkToplevel(self.pencere)
        self.acilir_menu.overrideredirect(True)
        self.acilir_menu.attributes("-topmost", True)

        cerceve = ctk.CTkFrame(
            self.acilir_menu,
            corner_radius=8,
            border_width=1,
            border_color=("gray75", "gray35"),
        )
        cerceve.pack(fill="both", expand=True)

        ctk.CTkButton(
            cerceve,
            text="Dosyalar...",
            anchor="w",
            fg_color="transparent",
            text_color=("gray15", "gray90"),
            hover_color=("gray85", "gray25"),
            height=30,
            command=self.menu_dosya_sec,
        ).pack(fill="x", padx=4, pady=(4, 2))

        ctk.CTkButton(
            cerceve,
            text="Klasör...",
            anchor="w",
            fg_color="transparent",
            text_color=("gray15", "gray90"),
            hover_color=("gray85", "gray25"),
            height=30,
            command=self.menu_klasor_sec,
        ).pack(fill="x", padx=4, pady=(2, 4))

        self.acilir_menu.update_idletasks()
        x = self.gorsel_ekle_btn.winfo_rootx()
        y = self.gorsel_ekle_btn.winfo_rooty() + self.gorsel_ekle_btn.winfo_height() + 4
        self.acilir_menu.geometry(f"130x72+{x}+{y}")

    def menu_dosya_sec(self):
        self.acilir_menuyu_kapat()
        self.dosya_ekle()

    def menu_klasor_sec(self):
        self.acilir_menuyu_kapat()
        self.klasor_ekle()

    def disariya_tiklandi(self, olay):
        if self.acilir_menu and self.acilir_menu.winfo_exists():
            mx = self.acilir_menu.winfo_rootx()
            my = self.acilir_menu.winfo_rooty()
            mw = self.acilir_menu.winfo_width()
            mh = self.acilir_menu.winfo_height()
            bx = self.gorsel_ekle_btn.winfo_rootx()
            by = self.gorsel_ekle_btn.winfo_rooty()
            bw = self.gorsel_ekle_btn.winfo_width()
            bh = self.gorsel_ekle_btn.winfo_height()
            if not (mx <= olay.x_root <= mx + mw and my <= olay.y_root <= my + mh) and not (bx <= olay.x_root <= bx + bw and by <= olay.y_root <= by + bh):
                self.acilir_menuyu_kapat()

    def dosya_ekle(self):
        dosya_yollari = filedialog.askopenfilenames(
            filetypes=[
                ("Görüntü Dosyaları", "*.jpg;*.jpeg;*.png;*.gif;*.bmp;*.tiff;*.tif"),
                ("Tüm Dosyalar", "*.*"),
            ]
        )
        for dosya_yolu in dosya_yollari:
            self.dosya_listeye_ekle(dosya_yolu)

    def klasor_ekle(self):
        klasor_yolu = filedialog.askdirectory()
        if not klasor_yolu:
            return
        for dosya_adi in os.listdir(klasor_yolu):
            tam_yol = os.path.join(klasor_yolu, dosya_adi)
            if os.path.isfile(tam_yol):
                uzanti = os.path.splitext(dosya_adi)[1].lower()
                if uzanti in DESTEKLENEN_UZANTILAR:
                    self.dosya_listeye_ekle(tam_yol)

    def suruklenme_basla(self, olay):
        self.liste_cercevesi.configure(
            border_width=2, border_color=("#1a73e8", "#58a6ff")
        )

    def suruklenme_bitti(self, olay):
        self.liste_cercevesi.configure(border_width=0)

    def dosya_birakildi(self, olay):
        self.liste_cercevesi.configure(border_width=0)
        yollar = self.birakilan_yollari_ayikla(olay.data)
        for yol in yollar:
            if os.path.isdir(yol):
                for dosya_adi in os.listdir(yol):
                    tam_yol = os.path.join(yol, dosya_adi)
                    if os.path.isfile(tam_yol):
                        uzanti = os.path.splitext(dosya_adi)[1].lower()
                        if uzanti in DESTEKLENEN_UZANTILAR:
                            self.dosya_listeye_ekle(tam_yol)
            elif os.path.isfile(yol):
                self.dosya_listeye_ekle(yol)

    def birakilan_yollari_ayikla(self, veri):
        yollar = []
        i = 0
        while i < len(veri):
            if veri[i] == "{":
                j = veri.index("}", i)
                yollar.append(veri[i + 1 : j])
                i = j + 2
            elif veri[i] == " ":
                i += 1
            else:
                j = veri.find(" ", i)
                if j == -1:
                    yollar.append(veri[i:])
                    break
                yollar.append(veri[i:j])
                i = j + 1
        return yollar

    def dosya_listeye_ekle(self, dosya_yolu):
        if dosya_yolu in self.dosyalar:
            return
        self.dosyalar.append(dosya_yolu)
        self.ipucu_guncelle()

        satir = ctk.CTkFrame(self.liste_cercevesi)
        satir.pack(fill="x", pady=1)
        self.satir_widgetleri.append(satir)

        ctk.CTkButton(
            satir,
            text="−",
            width=28,
            height=28,
            fg_color="transparent",
            border_width=1,
            border_color=("gray65", "gray45"),
            text_color=("gray15", "gray90"),
            hover_color=("gray85", "gray25"),
            command=lambda s=satir, d=dosya_yolu: self.dosya_kaldir(s, d),
        ).pack(side="left", padx=(5, 2), pady=2)

        dosya_adi = os.path.basename(dosya_yolu)
        ctk.CTkLabel(satir, text=dosya_adi, anchor="w").pack(
            side="left", fill="x", expand=True, padx=5
        )

        try:
            boyut = os.path.getsize(dosya_yolu)
            boyut_metni = boyut_formatla(boyut)
        except OSError:
            boyut_metni = "?"

        ctk.CTkLabel(satir, text=boyut_metni, anchor="e", text_color="gray").pack(
            side="right", padx=(5, 10)
        )

        self.sayac_guncelle()

    def dosya_kaldir(self, satir, dosya_yolu):
        satir.destroy()
        if dosya_yolu in self.dosyalar:
            self.dosyalar.remove(dosya_yolu)
        if satir in self.satir_widgetleri:
            self.satir_widgetleri.remove(satir)
        self.sayac_guncelle()
        self.ipucu_guncelle()

    def tumunu_temizle(self):
        self.dosyalar.clear()
        for satir in self.satir_widgetleri:
            satir.destroy()
        self.satir_widgetleri.clear()
        self.sayac_guncelle()
        self.ipucu_guncelle()

    def sayac_guncelle(self):
        sayi = len(self.dosyalar)
        if sayi == 0:
            self.sayac_etiketi.configure(text="")
        else:
            self.sayac_etiketi.configure(text=f"{sayi} görsel eklendi")

    def ipucu_guncelle(self):
        if self.dosyalar:
            self.birakma_ipucu.pack_forget()
        else:
            self.birakma_ipucu.pack(expand=True, pady=50)

    def cikti_klasoru_sec(self):
        klasor_yolu = filedialog.askdirectory()
        if klasor_yolu:
            self.cikti_klasoru = klasor_yolu
            self.cikti_etiketi.configure(text=f"Çıktı: {klasor_yolu}")

    def exif_temizle(self):
        if not self.dosyalar:
            self.uyari_goster("Uyarı", "Hedef saptanmadı.")
            return
        if self.islem_devam_ediyor:
            return
        self.islem_devam_ediyor = True
        self.butonlari_kilitle(True)
        self.ilerleme_etiketi.configure(text="EXIF bilgileri yok ediliyor...")
        self.ilerleme_cubugu.set(0)
        is_parcacigi = threading.Thread(
            target=self.exif_temizle_arkaplanda, daemon=True
        )
        is_parcacigi.start()

    def exif_temizle_arkaplanda(self):
        toplam = len(self.dosyalar)
        basarili = 0
        hatali = 0
        for sira, dosya_yolu in enumerate(self.dosyalar):
            try:
                gorsel = Image.open(dosya_yolu)
                uzanti = os.path.splitext(dosya_yolu)[1].lower()
                kayit_formati = FORMAT_ESLEME.get(uzanti, gorsel.format)
                cikti_yolu = (
                    os.path.join(self.cikti_klasoru, os.path.basename(dosya_yolu))
                    if self.cikti_klasoru
                    else dosya_yolu
                )
                if "exif" in gorsel.info:
                    temiz_gorsel = Image.new(gorsel.mode, gorsel.size)
                    temiz_gorsel.putdata(list(gorsel.getdata()))
                    kayit_ayarlari = {}
                    if "icc_profile" in gorsel.info:
                        kayit_ayarlari["icc_profile"] = gorsel.info["icc_profile"]
                    temiz_gorsel.save(cikti_yolu, kayit_formati, **kayit_ayarlari)
                else:
                    gorsel.save(cikti_yolu, kayit_formati)
                basarili += 1
            except Exception:
                hatali += 1
            ilerleme = (sira + 1) / toplam
            self.pencere.after(0, self.ilerleme_guncelle, ilerleme)
        self.pencere.after(0, self.islem_tamamlandi, basarili, hatali)

    def ilerleme_guncelle(self, deger):
        self.ilerleme_cubugu.set(deger)

    def islem_tamamlandi(self, basarili, hatali):
        self.islem_devam_ediyor = False
        self.butonlari_kilitle(False)
        if hatali > 0:
            self.ilerleme_etiketi.configure(
                text=f"{basarili} görselin EXIF bilgisi yok edildi. {hatali} görsel kaçtı."
            )
        else:
            self.ilerleme_etiketi.configure(
                text=f"{basarili} görselin EXIF bilgisi yok edildi."
            )

    def butonlari_kilitle(self, kilit):
        durum = "disabled" if kilit else "normal"
        self.gorsel_ekle_btn.configure(state=durum)
        self.cikti_sec_btn.configure(state=durum)
        self.tumunu_temizle_btn.configure(state=durum)
        self.arindir_btn.configure(state=durum)

    def bilgi_goster(self):
        hakkinda = ctk.CTkToplevel(self.pencere)
        hakkinda.title("Hakkında")
        hakkinda.geometry("420x230")
        hakkinda.resizable(False, False)
        hakkinda.grab_set()
        hakkinda.after(10, hakkinda.focus_force)

        if self.simge_yolu and os.path.exists(self.simge_yolu):
            try:
                hakkinda.iconbitmap(self.simge_yolu)
                hakkinda.after(200, lambda: hakkinda.iconbitmap(self.simge_yolu))
            except Exception:
                pass

        ctk.CTkLabel(
            hakkinda,
            text=PROGRAM_ADI,
            font=ctk.CTkFont(size=18, weight="bold"),
        ).pack(pady=(20, 8))

        ctk.CTkLabel(
            hakkinda,
            text="BMP, GIF, JPG, PNG ve TIFF dosyalarını\nEXIF üstverilerinden arındırır.",
            justify="center",
        ).pack(pady=4)

        ctk.CTkLabel(
            hakkinda,
            text="Farklı bir çıktı klasörü seçilmezse üstveriden arındırılan\ngörsel özgün görselin üzerine yazılır.",
            justify="center",
            text_color="gray",
            font=ctk.CTkFont(size=11),
        ).pack(pady=4)

        gelistirici_cercevesi = ctk.CTkFrame(hakkinda, fg_color="transparent")
        gelistirici_cercevesi.pack(pady=4)

        ctk.CTkLabel(gelistirici_cercevesi, text="Geliştirici:").pack(side="left")

        ctk.CTkButton(
            gelistirici_cercevesi,
            text=PROGRAM_GELISTIRICI,
            fg_color="transparent",
            text_color=("#1a73e8", "#58a6ff"),
            hover=False,
            width=70,
            command=lambda: webbrowser.open(GELISTIRICI_BAGLANTISI),
        ).pack(side="left")

        ctk.CTkButton(
            hakkinda, text="Kapat", command=hakkinda.destroy
        ).pack(pady=(8, 15))

    def kapatildiginda(self):
        self.acilir_menuyu_kapat()
        if self.gecici_simge_mi and self.simge_yolu and os.path.exists(self.simge_yolu):
            try:
                os.remove(self.simge_yolu)
            except Exception:
                pass
        if self.unlem_ico_yolu and os.path.exists(self.unlem_ico_yolu):
            try:
                os.remove(self.unlem_ico_yolu)
            except Exception:
                pass
        self.pencere.destroy()


if __name__ == "__main__":
    uygulama = SurukleBirakPencere()
    ExifYokEdiciUygulama(uygulama)
    uygulama.mainloop()
